### PR TITLE
added navbar and table for sections

### PR DESCRIPTION
**Pull request by alenavershinina**

### CODE REVIEW

**Review by milack68 — APPROVED** [review]

**Review by Cosnavel — CHANGES_REQUESTED** [review]
@milack68 das ist in meinen Augen Work in Progress und ein Draft

**Comment by thelf** [comment]
Ok und was bedeutet das bzw. was wäre der nächste Schritt @milack68 ?

**Comment by milack68** [comment]
@thelf Das bedeutet, dass der Code noch nicht vollständig fertig ist, um gemergt zu werden. Wir schauen uns das gemeinsam beim nächsten Codemeetup an wie man da am besten weiter mit dem pull request vorgeht.

**Comment by thelf** [comment]
Ok alles klar!

**Review by thelf — APPROVED** [review]

**Comment by alenavershinina** [comment]
@Cosnavel I added some changes to our home page. I think it looks better now (or still not good enough to merge?). I would like to work further with it, but I'm afraid, that we make the same work double with @thelf . Wasn't it better to merge, what we have for now, and then we (with @thelf und Anette) could decide, who makes concrete features? Should I make a new pull request with what I have now?
Снимок экрана от 2021-02-15 22-42-00
Снимок экрана от 2021-02-15 22-41-27

**Comment by Cosnavel** [comment]
@alenavershinina, I have never said it's not "good" enough. I just thought it's still a work in progress. Totally agree with your position. I will review and merge this pull request, and you can smoothly go further with new ones 😄

**Review by Cosnavel — APPROVED** [review]
✅

**Comment by thelf** [comment]
@Cosnavel suggested we could write our names in the comment section in GitHub, so we can see who is working with the issue. Later he want us to show how we assign an issue to a person.

**Pull request merged**
